### ISSUE TITLE
Installer stuck on Installing

### ISSUE THREAD

**Issue by muhdsalm** [blend-os/blendOS#21]
The installer is stuck on 'Installing blendOS'. I have manual partitioning selected. The console part is empty and the cpu (according to the system monitor) of 'jade-gui' is 0.00%. It says it may take some time but why is it not even doing anything?

**Comment by muhdsalm** [comment]
Here is the error in the terminal:
```
Traceback (most recent call last):
  File "/usr/share/jade-gui/jade_gui/window.py", line 214, in next
    self.on_page_change(page)
  File "/usr/share/jade-gui/jade_gui/window.py", line 206, in on_page_change
    page.on_show()
  File "/usr/share/jade-gui/jade_gui/functions/summary_screen.py", line 124, in on_show
    self.installprefs = InstallPrefs(
  File "/usr/share/jade-gui/jade_gui/classes/install_prefs.py", line 48, in __init__
    self.disk = disk.disk
AttributeError: 'NoneType' object has no attribute 'disk'
Traceback (most recent call last):
  File "/usr/share/jade-gui/jade_gui/window.py", line 214, in next
    self.on_page_change(page)
  File "/usr/share/jade-gui/jade_gui/window.py", line 206, in on_page_change
    page.on_show()
  File "/usr/share/jade-gui/jade_gui/functions/install_screen.py", line 50, in on_show
    prefs = self.window.summary_screen.installprefs.generate_json()
```

**Comment by pragmaticmero** [comment]
Maybe ur trying to use BIOS, this distro only works with UEFI. I didn't have problems when flashing with etcher. But when I tried booting with Ventoy it didn't work, idk why, well, try different things I guess.

**Comment by muhdsalm** [comment]
I would assume that if I were using BIOS it wouldn't boot at all. I am using uefi, on a usb flashed with balenaEtcher. I guess I could try flashing with a different app, though I think it wouldn't make much difference.

**Comment by Samia-47** [comment]
facing same problem. and it's not due to UEFI it's the problem of installer

**Comment by muhdsalm** [comment]
Alright, after messing around in a vm, here's the solution:
1. In automatic install, select the disk you want to install to.
2. Then click on manual partitioning and do it.
3. Continue normally

The problem, in my opinion, is that the installer throws an error because it has no disks to install to, even though we have selected the partitions. Once we select a disk, the installer then has a disk, and does our manual partitioning. I assume if I were to install to a partition that was in a disk that I had not selected, it would again throw an error.

But maybe it ignores the manual partitioning and goes ahead and does an automatic install, but when I tried it did not touch some free space I had in my vm. But do backup just in case.

I am leaving it open so the dev(s) see it and hopefully make it unnecessary to select a disk while manual partitioning. Please acknowledge by closing the issue.

**Comment by johanesPao** [comment]
> Alright, after messing around in a vm, here's the solution:
> 
>     1. In automatic install, select the disk you want to install to.
> 
>     2. Then click on manual partitioning and do it.
> 
>     3. Continue normally
> 
> 
> The problem, in my opinion, is that the installer throws an error because it has no disks to install to, even though we have selected the partitions. Once we select a disk, the installer then has a disk, and does our manual partitioning. I assume if I were to install to a partition that was in a disk that I had not selected, it would again throw an error.
> 
> But maybe it ignores the manual partitioning and goes ahead and does an automatic install, but when I tried it did not touch some free space I had in my vm. But do backup just in case.
> 
> I am leaving it open so the dev(s) see it and hopefully make it unnecessary to select a disk while manual partitioning. Please acknowledge by closing the issue.

I can confirm this to work in my case. Selecting disk in automatic install and then change to manual partition works.
Seems that the installer needs disk to be selected in automatic installing section.

**Comment by Samia-47** [comment]
> Alright, after messing around in a vm, here's the solution:
> 
> 1. In automatic install, select the disk you want to install to.
> 2. Then click on manual partitioning and do it.
> 3. Continue normally
> 
> The problem, in my opinion, is that the installer throws an error because it has no disks to install to, even though we have selected the partitions. Once we select a disk, the installer then has a disk, and does our manual partitioning. I assume if I were to install to a partition that was in a disk that I had not selected, it would again throw an error.
> 
> But maybe it ignores the manual partitioning and goes ahead and does an automatic install, but when I tried it did not touch some free space I had in my vm. But do backup just in case.
> 
> I am leaving it open so the dev(s) see it and hopefully make it unnecessary to select a disk while manual partitioning. Please acknowledge by closing the issue.

screensots guide needed ! Please.

**Comment by rishuriya** [comment]
![Screenshot from 2023-02-03 17-25-34](https://user-images.githubusercontent.com/85174423/216609557-6d377bd8-6693-445c-92e4-25ee2f73d91e.png)
It struck here from 10 minutes.

**Comment by hanifqas** [comment]
> Alright, after messing around in a vm, here's the solution:
> 
> 1. In automatic install, select the disk you want to install to.
> 
> 2. Then click on manual partitioning and do it.
> 
> 3. Continue normally
> 
> 
> 
> The problem, in my opinion, is that the installer throws an error because it has no disks to install to, even though we have selected the partitions. Once we select a disk, the installer then has a disk, and does our manual partitioning. I assume if I were to install to a partition that was in a disk that I had not selected, it would again throw an error.
> 
> 
> 
> But maybe it ignores the manual partitioning and goes ahead and does an automatic install, but when I tried it did not touch some free space I had in my vm. But do backup just in case.
> 
> 
> 
> I am leaving it open so the dev(s) see it and hopefully make it unnecessary to select a disk while manual partitioning. Please acknowledge by closing the issue.

I use this method. It working for me. I tried also it did not touch any partition for my windows. It only touch partition linux that i already format and prepared to install it.

**Comment by UserWillie** [comment]
Jumper EZpad mini 5
blendOS-2023.04.22-x86_64-plasma.iso

Installation gets stuck ... 😲
![Installation gets stuck](https://user-images.githubusercontent.com/124140409/235109618-7aa7ded9-a302-4841-88fc-77c42b8b118e.jpeg)

**Comment by MilkyWayboi** [comment]
> Jumper EZpad mini 5 blendOS-2023.04.22-x86_64-plasma.iso
> 
> Installation gets stuck ... astonished ![Installation gets stuck](https://user-images.githubusercontent.com/124140409/235109618-7aa7ded9-a302-4841-88fc-77c42b8b118e.jpeg)

Same Here
i was Using UEFI
but after reading this thread i think its because i use Ventoy

**Comment by MuchHustle** [comment]
It takes awhile, just wait. As hard as it is, just watch tv or something and wait for it to finish.
