### ISSUE TITLE
Android apps won't launch 

### ISSUE THREAD

**Issue by PDXUser** [blend-os/blendOS#58]
I am test driving this in a KVM using Libvirt on the host.  I can install the app stores without issue, but nothing from the Android base will work on the KDE Plasma spin on the latest release.  

Additionally, the apps show in the Lost and Found menu folder but that is about it, you can click on them, they act like they are launching but don't.

**Comment by blankcdf** [comment]
Good Evening, I am having a similar issue but the app stores will not open up at all. Any luck?

**Comment by hgwaysamurai** [comment]
> Good Evening, I am having a similar issue but the app stores will not open up at all. Any luck?

I don't know about in a virtual machine environment but once the OS is installed, I found that in the KDE Plasma spin, one would have to initialize Waydroid using the terminal (waydroid init) and it will open the app store.

**Comment by blankcdf** [comment]
> > Good Evening, I am having a similar issue but the app stores will not open up at all. Any luck?
> 
> I don't know about in a virtual machine environment but once the OS is installed, I found that in the KDE Plasma spin, one would have to initialize Waydroid using the terminal (waydroid init) and it will open the app store.

Thank you for the suggestion! I have attempted that and received the error relating to the module gbinder. Even after installing it myself I am still getting the same error. Thank you for the information! 

[blendyboy@blend ~]$ waydroid init
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init, wait_for_init, remote_init_client
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'

**Comment by hgwaysamurai** [comment]
> 

I think it has to be an error with python being updated. If you type in python --version, at least in mine it is 3.11.3 but the g-binder points to version 3.10 (pacman -Ql python-gbinder).

**Comment by blankcdf** [comment]
> > 
> 
> I think it has to be an error with python being updated. If you type in python --version, at least in mine it is 3.11.3 but the g-binder points to version 3.10 (pacman -Ql python-gbinder).

Hey thanks for the comment I checked it out and mine is the same version. Appreciate the information!

**Comment by hgwaysamurai** [comment]
> > > 
> > 
> > 
> > I think it has to be an error with python being updated. If you type in python --version, at least in mine it is 3.11.3 but the g-binder points to version 3.10 (pacman -Ql python-gbinder).
> 
> Hey thanks for the comment I checked it out and mine is the same version. Appreciate the information!

There is a new update that fixed the python binder, but since the new updates also introduced the 6.3.1-arch1-1 kernel update, then waydroid is still unable to be initialized as binder node "binder" for waydroid not found.

**Comment by catmeow72** [comment]
python binder is broken again for the same exact reason, but with the python 3.13 update this time.
